# RCRG_R1_C1.yml

model:        
  num_classes: 
    person_activity: 9

  num_clases_label:
    person_activity: ["Waiting", "Setting", "Digging", "Falling", "Spiking", "Blocking", "Jumping", "Moving", "Standing"]

training:    
  person_activity:
    batch_size: 512
    learning_rate: 0.0004 # 4e-4
    epochs: 15
    optimizer: "AdamW"
    # momentum: 0.9
    weight_decay: 1
    label_smoothing: 0.01
    
data:
  dataset_name: "GroupActivityDataset"
  data_dir: "data"
  annot_path: "data/annot_all.pkl"
  videos_path: "data/videos"

  video_splits:
    train: [1, 3, 6, 7, 10, 13, 15, 16, 18, 22, 23, 31, 32, 36, 38, 39, 40, 41, 42, 48, 50, 52, 53, 54]
    validation: [0, 2, 8, 12, 17, 19, 24, 26, 27, 28, 30, 33, 46, 49, 51]
    test: [4, 5, 9, 11, 14, 20, 21, 25, 29, 34, 35, 37, 43, 44, 45, 47]

experiment:
  name: "pa_cls" # person_activity_classifier 
  version: 1
  seed: 31
  description: "pretrained Resnet50 network is fined tuned for a person represention"