# RCRG_R1_C1.yml

model:        
  num_classes: 
    person_activity: 9
    group_activity: 8

  num_clases_label:
    group_activity: ["r_set", "r_spike" , "r-pass", "r_winpoint", "l_winpoint", "l-pass", "l-spike", "l_set"]

training:    
  group_activity:
    batch_size: 64
    learning_rate: 0.00005 # 5e-5
    epochs: 20
    optimizer: "AdamW"
    # momentum: 0.9
    weight_decay: 1
    label_smoothing: 0.05
    
data:
  dataset_name: "GroupActivityDataset"
  data_dir: "data"
  annot_path: "data/annot_all.pkl"
  videos_path: "data/videos"

  video_splits:
    train: [1, 3, 6, 7, 10, 13, 15, 16, 18, 22, 23, 31, 32, 36, 38, 39, 40, 41, 42, 48, 50, 52, 53, 54]
    validation: [0, 2, 8, 12, 17, 19, 24, 26, 27, 28, 30, 33, 46, 49, 51]
    test: [4, 5, 9, 11, 14, 20, 21, 25, 29, 34, 35, 37, 43, 44, 45, 47]

experiment:
  name: "RCRG_1R_1C_untuned"
  version: 1
  seed: 31
  description: "Using pretrained Resnet50 network to represent person with 2048-d features
then a single relational layer (1R), all people in 1 clique (1C) so all-pairs relationships
are learned."

# experiment:
#   name: "RCRG_R1_C1"
#   version: 1
#   seed: 31
#   description: "pretrained Resnet50 network is fined tuned and a person is represented with 4096-d features
# then a single relational layer (1R), all people in 1 clique (1C) so all-pairs relationships
# are learned."